# Generated by Django 6.0 on 2025-12-18 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Visita",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_visitante", models.CharField(max_length=100)),
                (
                    "rut",
                    models.CharField(help_text="Formato: 12.345.678-9", max_length=12),
                ),
                ("motivo", models.TextField()),
                (
                    "empresa_procedencia",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("fecha_ingreso", models.DateTimeField(auto_now_add=True)),
                ("fecha_salida", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Visita",
                "verbose_name_plural": "Registro de Visitas",
                "ordering": ["-fecha_ingreso"],
            },
        ),
    ]
