# Generated by Django 6.0 on 2025-12-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visitas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mensaje",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("autor", models.CharField(default="Anónimo", max_length=100)),
                ("texto", models.TextField()),
                ("fecha", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
